// Package router writes the llama-server router-mode preset file: one INI
// section per model with that model's launch plan, so a model loaded on
// demand through the API gets the same GPU/CPU split, context and sampling
// settings as one started from the control panel.
//
// Format (common/preset.cpp): "[name]" sections, "key = value" lines with
// keys being long flag names without dashes. Values run to the end of the
// line or to a ';' or '#', with no quoting or escaping, so values holding
// those characters can't be written.
package router

import (
	"fmt"
	"regexp"
	"strings"
)

// Entry is one model the router can load.
type Entry struct {
	// Name is the id API clients use in "model"; Path is the GGUF file (any
	// shard). A Path-less entry configures a model the router already
	// knows by that name, e.g. one it downloaded into its own cache.
	Name string
	Path string
	Args []string // llama-server flags for this model, --model excluded
}

// flags the router owns or that must not be set per model
var routerOwned = map[string]bool{
	"model": true, "host": true, "port": true, "alias": true, "api-key": true,
	"models-preset": true, "models-max": true, "models-dir": true,
}

var unsafeName = regexp.MustCompile(`[\[\]:;#\r\n]+`)

// SafeName turns a display name into a section id: ':' would be read as a
// quantization tag, and brackets, ';' and '#' break the INI syntax.
func SafeName(name string) string {
	s := strings.TrimSpace(unsafeName.ReplaceAllString(name, "-"))
	if s == "" {
		s = "model"
	}
	return s
}

// UniqueNames makes names distinct by suffixing repeats with -2, -3, ...
func UniqueNames(names []string) []string {
	seen := map[string]int{}
	out := make([]string, len(names))
	for i, n := range names {
		seen[n]++
		if seen[n] == 1 {
			out[i] = n
			continue
		}
		for k := seen[n]; ; k++ {
			c := fmt.Sprintf("%s-%d", n, k)
			if seen[c] == 0 {
				seen[c] = 1
				out[i] = c
				break
			}
		}
	}
	return out
}

// INI renders the preset file. Settings that can't be represented, or
// (when known is non-nil) that this llama-server doesn't recognize, are
// left out and reported: the router rejects the whole file, and so every
// model, over one unknown key.
func INI(entries []Entry, known map[string]bool) (string, []error) {
	var b strings.Builder
	var errs []error
	b.WriteString("; generated by Q38FNInference; rewritten when models change\nversion = 1\n")
	for _, e := range entries {
		fmt.Fprintf(&b, "\n[%s]\n", e.Name)
		if e.Path != "" {
			if !safeValue(e.Path) {
				errs = append(errs, fmt.Errorf("%s: path %q contains ';' or '#'; the router can't load it", e.Name, e.Path))
				continue
			}
			fmt.Fprintf(&b, "model = %s\n", e.Path)
		}
		for _, kv := range argsToKV(e.Args) {
			if routerOwned[kv[0]] {
				continue
			}
			if known != nil && !known[kv[0]] {
				errs = append(errs, fmt.Errorf("%s: --%s is not an option of this llama-server and was left out", e.Name, kv[0]))
				continue
			}
			if !safeValue(kv[1]) {
				errs = append(errs, fmt.Errorf("%s: --%s value %q contains ';' or '#' and was left out", e.Name, kv[0], kv[1]))
				continue
			}
			fmt.Fprintf(&b, "%s = %s\n", kv[0], kv[1])
		}
	}
	return b.String(), errs
}

var flagRe = regexp.MustCompile(`--[a-z0-9][a-z0-9-]*`)

// KnownFlags extracts the long option names (without dashes) from
// llama-server --help output.
func KnownFlags(help string) map[string]bool {
	known := map[string]bool{}
	for _, f := range flagRe.FindAllString(help, -1) {
		known[strings.TrimPrefix(f, "--")] = true
	}
	return known
}

func safeValue(v string) bool { return !strings.ContainsAny(v, ";#\r\n") }

// argsToKV pairs "--flag value" and turns bare "--flag" into flag = true.
// A value is anything not starting with "--" (so "-1" stays a value).
func argsToKV(args []string) [][2]string {
	var out [][2]string
	for i := 0; i < len(args); i++ {
		a := args[i]
		if !strings.HasPrefix(a, "--") {
			continue // stray value; flags are always long-form here
		}
		key := strings.TrimPrefix(a, "--")
		if k, v, ok := strings.Cut(key, "="); ok {
			out = append(out, [2]string{k, v})
			continue
		}
		if i+1 < len(args) && !strings.HasPrefix(args[i+1], "--") {
			out = append(out, [2]string{key, args[i+1]})
			i++
			continue
		}
		out = append(out, [2]string{key, "true"})
	}
	return out
}
